name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (no publish)'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jetify-com/devbox-install-action@v0.14.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            devbox run release-dry-run
          else
            devbox run release
          fi
